<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite9a42da5a924036023adca411c17b42e
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MyApp\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MyApp\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite9a42da5a924036023adca411c17b42e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite9a42da5a924036023adca411c17b42e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite9a42da5a924036023adca411c17b42e::$classMap;

        }, null, ClassLoader::class);
    }
}
